services:
  njttcup-mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: localadmin
      MONGO_INITDB_ROOT_PASSWORD: thisisapassword
  njttcup-adminapp:
    image: cupkeeper.adminapp
    depends_on:
      - njttcup-mongo
    restart: always
    ports:
      - 8000:80
    build:
      context: .
      dockerfile: src/CupKeeper.AdminApp/Dockerfile
  njttcup-adminapi:
    image: cupkeeper.adminapi
    depends_on:
      - njttcup-mongo
    restart: always
    ports:
      - 8001:8080
    build:
      context: .
      dockerfile: src/CupKeeper.AdminApi/Dockerfile
  njttcup-orleanshost:
    image: cupkeeper.orleanshost
    depends_on:
      - njttcup-mongo
    build:
      context: .
      dockerfile: src/CupKeeper.OrleansHost/Dockerfile
